kind: Service
apiVersion: v1
metadata:
  labels:
    app: billing
  name: billing
  namespace: applications
spec:
  ports:
    - name: gateway
      port: 81
      targetPort: 8081
    - name: private
      port: 82
      targetPort: 8082
    - name: webhooks
      port: 80
      targetPort: 8080
  selector:
    app: billing
